## .github/workflows/deploy.yml
name: Agent CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Prompt Evaluation (CI)
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: python test_agent.py

      - name: Build and Push Docker Image (CD)
        run: |
          docker build -t ai-agent:${{ github.sha }} .
          echo "Docker Push to Registry Simulated"
